FROM node:18-bullseye

WORKDIR /app/src/index.ts

COPY package.json tsconfig.json ./
COPY src ./src
COPY public ./public
COPY tools ./tools

RUN npm install
RUN npm run build
RUN npm install -g tsx
RUN npm install -g typescript
RUN npm install -g nodemon

EXPOSE 3000

CMD ["nodemon", "--watch", "src", "--exec", "tsx", "src/index.ts"]   


